### ISSUE TITLE
CGO_ENABLED=0

### ISSUE THREAD

**Issue by SevensRequiem** [emarifer/go-echo-templ-htmx#2]
Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub"

**Comment by emarifer** [comment]
Hi, if you are on Linux, install `build-essential` and `libsqlite3-dev` [(see)](https://github.com/go-gorm/gorm/discussions/6095)

```bash
sudo apt-get install build-essential libsqlite3-dev
```
If your machine runs Windows, take a look at this [link](https://pkg.go.dev/github.com/mattn/go-sqlite3#readme-windows) in case it can help you

😀
