### ISSUE TITLE
fromProtected, isError

### ISSUE THREAD

**Issue by malaschitz** [emarifer/go-echo-templ-htmx#3]
These two variables are static. A large number of simultaneous requests can cause problems. Wouldn't it be better if these variables were stored in echo.Context ? Am I wrong ?

**Comment by emarifer** [comment]
> These two variables are static. A large number of simultaneous requests can cause problems. Wouldn't it be better if these variables were stored in echo.Context ? Am I wrong ?

You're right. I only did it this way for simplicity and speed, but, as you say, it can cause problems. I have removed those global flags and stored them in `echo.Context` and created a middleware to handle the `fromProtected` flag based on the authentication status on the `Home`, `Login` and `Register` pages.

You can see it in this [commit](https://github.com/emarifer/go-echo-templ-htmx/commit/43938822c258692af3fa0a00ba11f14cb25b083c).

Thank you for your advice.👌

**Comment by malaschitz** [comment]
Thanks. Great project !
