### ISSUE TITLE
no matching versions for query "latest"

### ISSUE THREAD

**Issue by johanguse** [emarifer/go-echo-templ-htmx#4]
Hey, hello!

After running `go mod tidy`  I got these errors. Is this something related to the new version of GO?

`go version go1.22.2 linux/amd64`

```
go: finding module for package github.com/emarifer/go-echo-templ-htmx/views/todo_views
go: finding module for package github.com/emarifer/go-echo-templ-htmx/views/auth_views
go: finding module for package github.com/emarifer/go-echo-templ-htmx/views/errors_pages
go: github.com/emarifer/go-echo-templ-htmx/handlers imports
        github.com/emarifer/go-echo-templ-htmx/views/auth_views: no matching versions for query "latest"
go: github.com/emarifer/go-echo-templ-htmx/handlers imports
        github.com/emarifer/go-echo-templ-htmx/views/errors_pages: no matching versions for query "latest"
go: github.com/emarifer/go-echo-templ-htmx/handlers imports
        github.com/emarifer/go-echo-templ-htmx/views/todo_views: no matching versions for query "latest"
```

**Comment by emarifer** [comment]
Hello, I don't think that's what it's about. Try regenerating the templates to instead create a set of functions that `Go` can understand. As I say in the [README.md](https://github.com/emarifer/go-echo-templ-htmx?tab=readme-ov-file#-setup) you must execute the following command in the project folder:

```
$ templ generate
```

Then run the `air` command and the application will start normally.

**Comment by emarifer** [comment]
🤦 I forgot to tell you that to generate the `Go` code corresponding to these templates you will have to download this [executable binary](https://github.com/a-h/templ/releases/tag/v0.2.476) from Github and place it in the PATH of your system.
